server:
  AppVersion: 1.0.0
  Port: :5006
  PprofPort: :5556
  Mode: Development
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

postgres:
  PostgresqlHost: postgres
  PostgresqlPort: 5432
  PostgresqlUser: ${POSTGRES_USER}
  PostgresqlPassword: ${POSTGRES_PASSWORD}
  PostgresqlDbname: links
  PostgresqlSslmode: false
  PgDriver: pgx
